/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/
module  -- shake: keep-all --deprecated_module: ignore

public import HodgeConjecture
public import Other.Algebra.Category.ModuleCat.Presheaf.ExteriorPower
public import Other.Algebra.Category.Ring.Basic
public import Other.Algebra.DeRham.Complex
public import Other.Algebra.Homology.MapArrowConeConnecting
public import Other.Algebra.Homology.MapExtendBettiComparison
public import Other.Algebra.Homology.MapHomologyShift
public import Other.AlgebraicGeometry.AlgebraicCycleSupport
public import Other.AlgebraicGeometry.BettiGlobalSectionsAdditivity
public import Other.AlgebraicGeometry.BettiSupportedOrdinaryConeComparison
public import Other.AlgebraicGeometry.BettiSupportedOrdinarySign
public import Other.AlgebraicGeometry.BettiSupportedRawOrdinaryComparison
public import Other.AlgebraicGeometry.BorelMooreCycleClass
public import Other.AlgebraicGeometry.ChowCycleClassDescent
public import Other.AlgebraicGeometry.ChowGroup
public import Other.AlgebraicGeometry.ChowGroupLift
public import Other.AlgebraicGeometry.ClosedImmersionPointNormalCoordinates
public import Other.AlgebraicGeometry.CompactlySupportedCohomology
public import Other.AlgebraicGeometry.ComplexPointCoclassOrientationComparison
public import Other.AlgebraicGeometry.ComplexPointCoclassSchemeIso
public import Other.AlgebraicGeometry.ComplexPointCoclassSheafIso
public import Other.AlgebraicGeometry.ComplexSupportCohomologySheafNormalization
public import Other.AlgebraicGeometry.ComplexSupportedOrdinaryComparison
public import Other.AlgebraicGeometry.CycleClass
public import Other.AlgebraicGeometry.CycleClassDimension
public import Other.AlgebraicGeometry.CycleComponentAnalyticEmbedding
public import Other.AlgebraicGeometry.CycleComponentAnalyticImmersion
public import Other.AlgebraicGeometry.CycleComponentBorelMoore
public import Other.AlgebraicGeometry.CycleComponentGlobalFundamentalClass
public import Other.AlgebraicGeometry.CycleComponentLocalOrientation
public import Other.AlgebraicGeometry.CycleComponentLocalOrientationCoherence
public import Other.AlgebraicGeometry.CycleComponentMaximalCodimensionPurity
public import Other.AlgebraicGeometry.CycleComponentPointBoundary
public import Other.AlgebraicGeometry.CycleComponentPointClassNormalization
public import Other.AlgebraicGeometry.CycleComponentPointCoclassSectionNormalization
public import Other.AlgebraicGeometry.CycleComponentPointOrdinarySign
public import Other.AlgebraicGeometry.CycleComponentPointPurity
public import Other.AlgebraicGeometry.CycleComponentRegularImmersion
public import Other.AlgebraicGeometry.DimensionedSmoothProjective
public import Other.AlgebraicGeometry.HodgeCodimensionZero
public import Other.AlgebraicGeometry.HypercohomologyFlasqueNaturality
public import Other.AlgebraicGeometry.OrderOfVanishing
public import Other.AlgebraicGeometry.PointCycleClass
public import Other.AlgebraicGeometry.PrincipalDivisorCycleClass
public import Other.AlgebraicGeometry.PrincipalDivisorDegreeReduction
public import Other.AlgebraicGeometry.ProjectiveAnalytificationConnected
public import Other.AlgebraicGeometry.ProjectiveAnalytificationLocallyContractible
public import Other.AlgebraicGeometry.ProjectiveAnalytificationSecondCountable
public import Other.AlgebraicGeometry.ProjectiveSingularCoefficientBaseChange
public import Other.AlgebraicGeometry.SheafBorelMoore
public import Other.AlgebraicGeometry.SheafBorelMoorePointClass
public import Other.AlgebraicGeometry.SheafCycleClass
public import Other.AlgebraicGeometry.SingularCycleClass
public import Other.AlgebraicGeometry.SmoothClosedCycleClass
public import Other.AlgebraicGeometry.SmoothClosedCycleClassRationalComparison
public import Other.AlgebraicGeometry.SmoothClosedCycleMorphism
public import Other.AlgebraicGeometry.SmoothClosedPointCoclassSectionNormalization
public import Other.AlgebraicGeometry.SmoothClosedPointPurityNormalization
public import Other.AlgebraicGeometry.SmoothClosedSupportLowestCohomology
public import Other.AlgebraicGeometry.SmoothClosedSupportedCycleMorphism
public import Other.AlgebraicGeometry.SmoothRegularLocal
public import Other.AlgebraicTopology.CechNerveEvaluation
public import Other.AlgebraicTopology.ChartLocalClassHomeomorph
public import Other.AlgebraicTopology.ChartLocalFundamentalClassInvariance
public import Other.AlgebraicTopology.ChartTargetPointClassNormalization
public import Other.AlgebraicTopology.ClosedEmbeddingConstantSectionClass
public import Other.AlgebraicTopology.ClosedEmbeddingDerivedPushforward
public import Other.AlgebraicTopology.ClosedEmbeddingSheafExact
public import Other.AlgebraicTopology.ClosedEmbeddingSheafification
public import Other.AlgebraicTopology.CohomologySheafOpenComparison
public import Other.AlgebraicTopology.CohomologySheafOpenRestriction
public import Other.AlgebraicTopology.CohomologySheafSectionNaturality
public import Other.AlgebraicTopology.CohomologySheafSectionRestriction
public import Other.AlgebraicTopology.CompactificationBorelMoore
public import Other.AlgebraicTopology.DerivedClosedSupportTruncation
public import Other.AlgebraicTopology.DerivedSheafSectionClass
public import Other.AlgebraicTopology.DerivedSheafSupportTruncation
public import Other.AlgebraicTopology.FiniteGoodCoverHomology
public import Other.AlgebraicTopology.FiniteGoodCoverNerveHomology
public import Other.AlgebraicTopology.FirstQuadrantColumnFiltration
public import Other.AlgebraicTopology.FirstQuadrantColumnFiltrationQuotient
public import Other.AlgebraicTopology.FirstQuadrantColumnFiltrationShortExact
public import Other.AlgebraicTopology.FirstQuadrantRowwiseTotalization
public import Other.AlgebraicTopology.FirstQuadrantTotalComplex
public import Other.AlgebraicTopology.GlobalFundamentalClass
public import Other.AlgebraicTopology.GlobalRawRelativeConnecting
public import Other.AlgebraicTopology.GraphNormalSlicePurity
public import Other.AlgebraicTopology.HorizontalTotalHomotopy
public import Other.AlgebraicTopology.IntegralCechTotalAugmentation
public import Other.AlgebraicTopology.OpenCoverOrderedCechBicomplex
public import Other.AlgebraicTopology.OpenRawRelativeConnecting
public import Other.AlgebraicTopology.OpenRestrictedLowestCohomologyNormalization
public import Other.AlgebraicTopology.OpenRestrictionStalk
public import Other.AlgebraicTopology.OrderedCechNormalization
public import Other.AlgebraicTopology.OrderedCechRealization
public import Other.AlgebraicTopology.OrderedCechTupleAlgebra
public import Other.AlgebraicTopology.PointSupportedChainSection
public import Other.AlgebraicTopology.RelativeCochainConeForgetComparison
public import Other.AlgebraicTopology.RelativeHomologyEmpty
public import Other.AlgebraicTopology.RelativeMayerVietoris
public import Other.AlgebraicTopology.SingularAmbientCapSheaf
public import Other.AlgebraicTopology.SingularCapNaturality
public import Other.AlgebraicTopology.SingularCapProduct
public import Other.AlgebraicTopology.SingularChainSheafClosedSupport
public import Other.AlgebraicTopology.SingularChainSheafDerivedPushforward
public import Other.AlgebraicTopology.SingularChainSheafOpenExcision
public import Other.AlgebraicTopology.SingularChainSheafOpenRestriction
public import Other.AlgebraicTopology.SingularChainSheafPushforward
public import Other.AlgebraicTopology.SingularCoefficientBaseChange
public import Other.AlgebraicTopology.SingularCohomologySupportNaturality
public import Other.AlgebraicTopology.SingularCohomologyZero
public import Other.AlgebraicTopology.SingularCohomologyZeroConnectedness
public import Other.AlgebraicTopology.SingularContractibleMapQuasiIso
public import Other.AlgebraicTopology.SingularCoverSmallPresentation
public import Other.AlgebraicTopology.SingularHomologyVanishing
public import Other.AlgebraicTopology.SingularMayerVietoris
public import Other.AlgebraicTopology.SingularOpenCoverSmallChains
public import Other.AlgebraicTopology.SingularPeriod
public import Other.AlgebraicTopology.SingularRelativeCapProduct
public import Other.AlgebraicTopology.SingularSubdivisionIteration
public import Other.AlgebraicTopology.SingularSupportCapProduct
public import Other.AlgebraicTopology.SingularTriadCapProduct
public import Other.AlgebraicTopology.SingularTriadExcision
public import Other.AlgebraicTopology.StandardSimplexSingularComparison
public import Other.AlgebraicTopology.SupportedSectionConeConnecting
public import Other.AlgebraicTopology.SupportedSingularOrdinaryComparison
public import Other.AlgebraicTopology.TopOpenRelativeCochainNormalization
public import Other.CommutativeAlgebra.RegularLocalQuotientKernel
public import Other.Topology.Category.TopCat.Basic
