/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/
module

public import Other.AlgebraicGeometry.CycleClass

/-!
# Descent of componentwise cycle classes to Chow groups

This auxiliary construction extends prescribed component classes to cycles and descends them
to rational Chow groups, conditional on vanishing on every principal divisor. It is not needed
to state the Hodge conjecture and deliberately lives outside the statement's import closure.
-/

@[expose] public noncomputable section

open CategoryTheory Order TopologicalSpace

namespace AlgebraicGeometry

universe u

/-- Extend prescribed classes of points additively to integral algebraic cycles on a compact
scheme. Compactness turns the locally finite support of an algebraic cycle into finite support,
so this is the usual finite sum of the coefficients times the prescribed point classes. -/
def cycleClassOnAlgebraicCycles {X : Scheme.{u}} [CompactSpace X]
    {M : Type*} [AddCommGroup M] (pointClass : X → M) :
    AlgebraicCycle X ℤ →+ M :=
  (Finsupp.linearCombination ℤ pointClass).toAddMonoidHom.comp compactCycleToFinsupp

/-- The class of an algebraic cycle is the finite linear combination of its point classes. -/
lemma cycleClassOnAlgebraicCycles_apply {X : Scheme.{u}} [CompactSpace X]
    {M : Type*} [AddCommGroup M] (pointClass : X → M) (c : AlgebraicCycle X ℤ) :
    cycleClassOnAlgebraicCycles pointClass c =
      (compactCycleToFinsupp c).sum fun x n ↦ n • pointClass x :=
  rfl

/-- Extend classes prescribed on the codimension-`p` points to all integral algebraic cycles,
using zero at points of every other codimension. This extension is useful for rational
equivalence: the subgroup of relations is first generated inside the group of all algebraic
cycles, before being pulled back to the pure codimension-`p` subgroup. -/
def cycleClassOnAlgebraicCyclesOfComponents {X : Scheme.{u}} [CompactSpace X] {p : ℕ}
    {M : Type*} [AddCommGroup M]
    (componentClass : ∀ (x : X), coheight x = p → M) : AlgebraicCycle X ℤ →+ M := by
  classical
  let componentValue : X → M := fun x ↦
    if hx : coheight x = p then componentClass x hx else 0
  exact cycleClassOnAlgebraicCycles componentValue

/-- Explicit finite-sum formula for the extension of codimension-`p` component classes to all
algebraic cycles. -/
lemma cycleClassOnAlgebraicCyclesOfComponents_apply
    {X : Scheme.{u}} [CompactSpace X] {p : ℕ}
    {M : Type*} [AddCommGroup M]
    (componentClass : ∀ (x : X), coheight x = p → M) (c : AlgebraicCycle X ℤ) :
    cycleClassOnAlgebraicCyclesOfComponents componentClass c =
      (compactCycleToFinsupp c).sum fun x n ↦
        n • if hx : coheight x = p then componentClass x hx else 0 :=
  rfl

/-- An additive map on all algebraic cycles kills the principal-divisor subgroup exactly when it
kills every principal-divisor generator. -/
lemma principalDivisorSubgroup_le_ker_iff
    {X : Scheme.{u}} {p : ℕ} {M : Type*} [AddCommGroup M]
    (f : AlgebraicCycle X ℤ →+ M) :
    principalDivisorSubgroup X p ≤ f.ker ↔
      ∀ D : PrincipalDivisor X p, f D.pushforwardCycle = 0 := by
  rw [principalDivisorSubgroup, AddSubgroup.closure_le]
  refine ⟨fun h D ↦ h (Set.mem_range_self D), ?_⟩
  rintro h _ ⟨D, rfl⟩
  exact h D

/-- To prove that the componentwise class map vanishes on the subgroup generated by principal
divisors, it suffices to prove the corresponding equality for each principal-divisor generator.
The statement lives on all algebraic cycles, matching the definition of
`principalDivisorSubgroup`. -/
lemma principalDivisorSubgroup_le_cycleClassOnAlgebraicCyclesOfComponents_ker
    {X : Scheme.{u}} [CompactSpace X] {p : ℕ}
    {M : Type*} [AddCommGroup M]
    (componentClass : ∀ (x : X), coheight x = p → M)
    (hprincipal : ∀ D : PrincipalDivisor X p,
      cycleClassOnAlgebraicCyclesOfComponents componentClass D.pushforwardCycle = 0) :
    principalDivisorSubgroup X p ≤
      (cycleClassOnAlgebraicCyclesOfComponents componentClass).ker :=
  (principalDivisorSubgroup_le_ker_iff
    (cycleClassOnAlgebraicCyclesOfComponents componentClass)).2 hprincipal

/-- Vanishing on every principal-divisor generator implies vanishing on every rational
equivalence between pure codimension-`p` cycles. This is the algebraic descent step; all
geometric content is concentrated in the generator equality `hprincipal`. -/
lemma rationalEquivalenceSubgroup_le_cycleClassOnCyclesOfComponents_ker
    {X : Scheme.{u}} [CompactSpace X] {p : ℕ}
    {M : Type*} [AddCommGroup M]
    (componentClass : ∀ (x : X), coheight x = p → M)
    (hprincipal : ∀ D : PrincipalDivisor X p,
      cycleClassOnAlgebraicCyclesOfComponents componentClass D.pushforwardCycle = 0) :
    rationalEquivalenceSubgroup X p ≤
      (cycleClassOnCyclesOfComponents componentClass).ker := fun _ hc ↦
  principalDivisorSubgroup_le_cycleClassOnAlgebraicCyclesOfComponents_ker
    componentClass hprincipal hc

namespace ChowGroup

/-- The integral Chow-group cycle-class map obtained from component classes after proving the
single geometric statement that every principal divisor has zero componentwise class. -/
def cycleClassOfComponents {X : Scheme.{u}} [CompactSpace X] {p : ℕ}
    {M : Type*} [AddCommGroup M]
    (componentClass : ∀ (x : X), coheight x = p → M)
    (hprincipal : ∀ D : PrincipalDivisor X p,
      cycleClassOnAlgebraicCyclesOfComponents componentClass D.pushforwardCycle = 0) :
    ChowGroup X p →+ M :=
  liftCycleClass (cycleClassOnCyclesOfComponents componentClass)
    (rationalEquivalenceSubgroup_le_cycleClassOnCyclesOfComponents_ker
      componentClass hprincipal)

/-- Evaluation of the componentwise Chow-group class map on a represented cycle. -/
@[simp] lemma cycleClassOfComponents_mk
    {X : Scheme.{u}} [CompactSpace X] {p : ℕ}
    {M : Type*} [AddCommGroup M]
    (componentClass : ∀ (x : X), coheight x = p → M)
    (hprincipal : ∀ D : PrincipalDivisor X p,
      cycleClassOnAlgebraicCyclesOfComponents componentClass D.pushforwardCycle = 0)
    (z : CodimensionCycle X p) :
    cycleClassOfComponents componentClass hprincipal (mk z) =
      cycleClassOnCyclesOfComponents componentClass z :=
  liftCycleClass_mk _ _ _

/-- The rational Chow-group cycle-class map determined by component classes and the theorem that
principal divisors have zero class. -/
def rationalCycleClassOfComponents {X : Scheme.{u}} [CompactSpace X] {p : ℕ}
    {M : Type*} [AddCommGroup M] [Module ℚ M]
    (componentClass : ∀ (x : X), coheight x = p → M)
    (hprincipal : ∀ D : PrincipalDivisor X p,
      cycleClassOnAlgebraicCyclesOfComponents componentClass D.pushforwardCycle = 0) :
    RationalChowGroup X p →ₗ[ℚ] M :=
  rationalExtension (cycleClassOfComponents componentClass hprincipal)

/-- A codimension-`p` component with coefficient one maps to its prescribed class under the
rational componentwise cycle-class map. -/
@[simp] lemma rationalCycleClassOfComponents_component
    {X : Scheme.{u}} [CompactSpace X] {p : ℕ}
    {M : Type*} [AddCommGroup M] [Module ℚ M]
    (componentClass : ∀ (x : X), coheight x = p → M)
    (hprincipal : ∀ D : PrincipalDivisor X p,
      cycleClassOnAlgebraicCyclesOfComponents componentClass D.pushforwardCycle = 0)
    (x : X) (hx : coheight x = p) :
    rationalCycleClassOfComponents componentClass hprincipal
        (toRational (mk (CodimensionCycle.single x hx 1))) =
      componentClass x hx := by
  rw [rationalCycleClassOfComponents, toRational_apply, rationalExtension_tmul,
    cycleClassOfComponents_mk, cycleClassOnCyclesOfComponents_single]
  simp

end ChowGroup

end AlgebraicGeometry
