/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/
module

public import HodgeConjecture.Definitions.AlgebraicGeometry.Coniveau
public import Other.AlgebraicGeometry.CycleClass

import HodgeConjecture.Lemmas.AlgebraicGeometry.RationalCohomologyZero
import Other.AlgebraicGeometry.CycleClassDimension
import Other.AlgebraicGeometry.ProjectiveAnalytificationConnected

/-!
# The Hodge conjecture in codimension zero

The genuine codimension-zero Chow cycle-class map has image equal to the line generated by the
degree-zero rational cohomology unit.  On a connected analytification, the computation of
degree-zero constant-sheaf cohomology identifies this line with the whole cohomology group.
Consequently the Hodge conjecture holds in codimension zero whenever analytic connectedness is
available.

For a smooth projective complex variety of complex dimension zero, analytic connectedness is
already known.  Combining the codimension-zero calculation with the dimension
bounds proves the Hodge-conjecture inclusion in every codimension for such a variety.
-/

@[expose] public noncomputable section

open CategoryTheory TopologicalSpace

namespace AlgebraicGeometry.ComplexPoint

open Point

variable (X : Over (Spec ↧ℂ)) [IsIntegral X.left] [Smooth X.hom]
  [IsProjective X.hom]

/-- On a connected projective analytification, the image of the genuine codimension-zero Chow
cycle-class map is all of degree-zero rational cohomology. -/
theorem codimensionZeroCycleClassSpan_eq_top_of_connected
    (hV : ConnectedSpace (ComplexPoint X)) :
    codimensionZeroCycleClassSpan X = ⊤ := by
  let : ConnectedSpace (ComplexPoint X) := hV
  rw [codimensionZeroCycleClassSpan_eq_span_unit, span_rationalCohomologyUnit_eq_top]

/-- On a connected projective analytification, the constructed codimension-zero algebraic
cycle-class span is the whole degree-zero rational cohomology group, provided it has been compared
with the separately constructed codimension-zero Chow-class span. -/
theorem algebraicCycleClassSpan_zero_eq_top_of_connected
    (hV : ConnectedSpace (ComplexPoint X))
    (hcompare : algebraicCycleClassSpan X 0 =
      codimensionZeroCycleClassSpan X) :
    algebraicCycleClassSpan X 0 = ⊤ := by
  rw [hcompare, codimensionZeroCycleClassSpan_eq_top_of_connected X hV]

/-- The degree-zero Hodge classes are exactly the algebraic cycle-class span when the
analytification is connected. -/
theorem rationalHodgeClasses_zero_eq_algebraicCycleClassSpan_of_connected

    (hV : ConnectedSpace (ComplexPoint X))
    (hcompare : algebraicCycleClassSpan X 0 =
      codimensionZeroCycleClassSpan X) :
    Hdg^0(ℚ; X) = algebraicCycleClassSpan X 0 := by
  rw [hodgeClasses_zero_eq_top,
    algebraicCycleClassSpan_zero_eq_top_of_connected X hV hcompare]

/-- The Hodge-conjecture inclusion holds in codimension zero when the analytification is
connected. -/
theorem rationalHodgeClasses_zero_le_algebraicCycleClassSpan_of_connected

    (hV : ConnectedSpace (ComplexPoint X))
    (hcompare : algebraicCycleClassSpan X 0 =
      codimensionZeroCycleClassSpan X) :
    Hdg^0(ℚ; X) ≤ algebraicCycleClassSpan X 0 := by
  rw [rationalHodgeClasses_zero_eq_algebraicCycleClassSpan_of_connected X hV hcompare]

/-- The Hodge-conjecture inclusion holds in every codimension for a smooth projective complex
variety of complex dimension zero. -/
theorem rationalHodgeClasses_le_algebraicCycleClassSpan_of_dimension_eq_zero
    (hd : dim X.left = 0)
    (hcompare : algebraicCycleClassSpan X 0 =
      codimensionZeroCycleClassSpan X) (p : ℕ) :
    Hdg^p(ℚ; X) ≤ algebraicCycleClassSpan X p := by
  by_cases hp : p = 0
  · subst p
    exact rationalHodgeClasses_zero_le_algebraicCycleClassSpan_of_connected X
      (connectedSpaceOfDimensionEqZero X (dim X.left) hd) hcompare
  · have hdim : dim X.left < p := by lia
    rw [hodgeClasses_eq_bot_of_lt ℚ X hdim,
      algebraicCycleClassSpan_eq_bot_of_lt X (dim X.left) p hdim]

end AlgebraicGeometry.ComplexPoint
